FROM baseimage
# Enable RPMFusion
# Doesn't work when Host Fedora Version != Toolbox Build Environment for whatever reason
RUN dnf install -y \
    "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" \
    "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"
    mpd \
    mpc \
    ncmpcpp \
    mpdris2 \
    && \
    dnf clean all
